### ISSUE TITLE
Alleged infringement 

### ISSUE THREAD

**Issue by Shawn-Armstrong** [kirbyfern/Verify_Kirby#1]
Hello Kirby Franandez,

A colleague has brought your repository to my attention, which appears to infringe on my protected and licensed work. Your initial commit, [140a77c7929d92c22598a56c28849a3d38de9eac](140a77c7929d92c22598a56c28849a3d38de9eac), is a near identical copy of my repository, [UCSC_Student_Website_Template](https://github.com/Shawn-Armstrong/UCSC_Student_Website_Template).

Additionally, this code was wrongfully committed under your username and email (kirbygit / kirbyjames.fernandez01@student.csulb.edu), and the project's license file, accrediting me as the copyright holder, is absent. 

Since this project is licensed under the MIT license, you are welcome to reuse the work, provided that proper attribution is given and the original license file is included as required by the license. **I respectfully request that you remove this repository.** Failure to comply may result in a formal DMCA takedown request.

Thank you for addressing this promptly.

**Comment by kirbyfern** [comment]
oh thanks I was just trying to work around on it not intentionally copying thanks

**Comment by kirbyfern** [comment]
> Hello Kirby Franandez,
> 
> A colleague has brought your repository to my attention, which appears to infringe on my protected and licensed work. Your initial commit, [140a77c7929d92c22598a56c28849a3d38de9eac](140a77c7929d92c22598a56c28849a3d38de9eac), is a near identical copy of my repository, [UCSC_Student_Website_Template](https://github.com/Shawn-Armstrong/UCSC_Student_Website_Template).
> 
> Additionally, this code was wrongfully committed under your username and email (kirbygit / [kirbyjames.fernandez01@student.csulb.edu](mailto:kirbyjames.fernandez01@student.csulb.edu)), and the project's license file, accrediting me as the copyright holder, is absent.
> 
> Since this project is licensed under the MIT license, you are welcome to reuse the work, provided that proper attribution is given and the original license file is included as required by the license. **I respectfully request that you remove this repository.** Failure to comply may result in a formal DMCA takedown request.
> 
> Thank you for addressing this promptly.

Sorry I forgot to add a new license under my name and tag you I was just working around with vue this time around thanks! @Shawn-Armstrong
